# Rustfmt configuration for UTPM
# See https://rust-lang.github.io/rustfmt/ for all options
# Only stable features are enabled by default

edition = "2024"

# Stable formatting options
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Imports
reorder_imports = true

# Misc stable options
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
match_block_trailing_comma = true

# Deprecated option replaced
fn_params_layout = "Tall"

# NOTE: Many formatting options require nightly Rust.
# To use advanced formatting features, install nightly and uncomment below:
#
# unstable_features = true
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# normalize_comments = true
# wrap_comments = true
# comment_width = 100
# format_code_in_doc_comments = true
# format_strings = true
# format_macro_matchers = true
# format_macro_bodies = true
# struct_lit_single_line = false
# fn_single_line = false
# where_single_line = false
# overflow_delimited_expr = true
# force_multiline_blocks = false
# brace_style = "SameLineWhere"
# control_brace_style = "AlwaysSameLine"
# trailing_comma = "Vertical"
